name: Build and Run Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and run credible cupid server
    - run: cp env.Sample .env
    - run: docker compose up --build --remove-orphans
